// react/50_shopping_app/04_stage_redux/frontend/src/components/Navbar.js
import {Link} from 'react-router-dom';
import {useSelector,useDispatch} from 'react-redux';
import {logout} from '../actions/loginActions';

const Navbar = (props) => {
	
	const state = useSelector(state => state);
	const dispatch = useDispatch();
	
	if(state.login.isLogged) {
		return (
			<nav className="navbar navbar-expand-lg navbar-light bg-light">
				<p className="navbar-brand" style={{marginLeft:10}}>Shopping App</p>
				<ul className="navbar-nav">
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/list">Shopping App</Link>
					</li>
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/form">Add new item</Link>
					</li>
					<li className="nav-item" style={{marginLeft:10}}>
						<Link to="/" onClick={() => dispatch(logout(state.login.token))}>Logout</Link>
					</li>
				</ul>
			</nav>
		)
	} else {
		return (
			<nav className="navbar navbar-expand-lg navbar-light bg-light">
				<p className="navbar-brand" style={{marginLeft:10}}>Shopping App</p>
			</nav>
		)
	}
}

export default Navbar;

// angular/k-shoppingapp/src/app/components/navbar.component.ts
import {Component} from '@angular/core';
import {LoginService} from '../services/login.service';
import {Router} from '@angular/router';

@Component({
	selector:"navbar",
	templateUrl:"./navbar.component.html"
})
export class Navbar {
	
	constructor(private login:LoginService,private router:Router) {}
	
	isUserLogged() {
		return this.login.isUserLogged()
	}
	
	logout() {
		this.login.logout().subscribe(
			(data) => console.log(data),
			(error) => {
				this.login.setLoginState(false,"");
				this.router.navigate(["/"])
			},
			() => {
				this.login.setLoginState(false,"");
				this.router.navigate(["/"])
			}
		)
	}
}
<div style="text-align:center">
	<nav class="navbar navbar-extend-lg navbar-light bg-light">
	<p class="navbar-brand">Shopping App</p>
	<ul class="navbar-nav" *ngIf="isUserLogged();else notLogged">
		<li class="nav-item">
			<a class="nav-link" routerLink="/list">Shopping List</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" routerLink="/form">Add new Item</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" routerLink="/" (click)="logout()">Logout</a>
		</li>
	</ul>
	<ng-template #notLogged>
		<ul class="navbar-nav"></ul>
	</ng-template>
	</nav>
</div>
