// react/60_typescript/05_shopping_app/src/components/ShoppingList.tsx
import React from 'react';
import ShoppingItem from '../models/ShoppingItem';

interface Props {
	list:ShoppingItem[];
	removeItem:(id:number) => void;
}

const ShoppingList:React.FC<Props> = (props:Props) => {
	
	let items = props.list.map((item) => {
		return(
			<tr key={item.id}>
				<td>{item.type}</td>
				<td>{item.count}</td>
				<td>{item.price}</td>
				<td><button onClick={() => props.removeItem(item.id)}>Remove</button></td>
			</tr>
		)
	})
	return (
		<table>
			<thead>
				<tr>
					<th>Type</th>
					<th>Count</th>
					<th>Price</th>
					<th>Remove</th>
				</tr>
			</thead>
			<tbody>
			{items}
			</tbody>
		</table>
	)
}

export default ShoppingList;

// angular/k-shoppingapp/src/app/components/shoppinglist.component.ts
import {Component,OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shopping.service';
import {LoginService} from '../services/login.service';
import {Router} from '@angular/router';

@Component({
	selector:"shoppinglist",
	templateUrl:"./shoppinglist.component.html"
})
export class ShoppingList implements OnInit {
	
	list:ShoppingItem[] = [];
	
	constructor(private shopping:ShoppingService,private login:LoginService,private router:Router){}
	
	ngOnInit() {
		if(this.login.isUserLogged()) {
			this.getList()
		} else {
			this.router.navigate(["/"])
		}
	}
	
	getList() {
		this.shopping.getList().subscribe(
			(data) => this.list = data,
			(error) => console.log(error),
			() => console.log("Get list done")
		)
	}
	
	removeItem(id:number) {
		this.shopping.removeItem(id).subscribe(
			(data) => this.getList(),
			(error) => console.log(error),
			() => console.log("Remove item done")
		)
	}
}
<table class="table table-striped">
	<thead>
		<th>Type</th>
		<th>Count</th>
		<th>Price</th>
		<th>Remove</th>
	</thead>
	<tbody>
		<tr *ngFor="let item of list">
			<td>{{item.type}}</td>
			<td>{{item.count}}</td>
			<td>{{item.price}}</td>
			<td><button class="btn btn-danger" (click)="removeItem(item.id)">Remove</button></td>
		</tr>
	</tbody>
</table>
