// react/16_hoc_and_context/src/components/ContactList.js
import React from 'react';
import ContactHandler from '../context/ContactHandler';

class ContactList extends React.Component {

	render() {
		let contacts = this.props.list.map((contact) => {
			return(
				<tr key={contact.id}>
					<td>{contact.firstname}</td>
					<td>{contact.lastname}</td>
					<td>{contact.email}</td>
					<td>{contact.phone}</td>
					<td><button onClick={() => this.props.removeContact(contact.id)}>Remove</button></td>
				</tr>
			)
		})
		return(
			<table>
				<thead>
					<tr>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Email</th>
						<th>Phone</th>
						<th>Remove</th>
					</tr>
				</thead>
				<tbody>
				{contacts}
				</tbody>
			</table>
		)
	}
}

export default ContactHandler(ContactList)

// angular/g-services/src/app/components/contactlist.component.ts
import {Component,OnInit} from '@angular/core';
import {Contact} from '../models/contact.model';
import {ContactService} from '../services/contact.service'

@Component({
	selector:"contact-list",
	templateUrl:"./contactlist.component.html"
})
export class ContactList implements OnInit {
	
	contact:Contact = new Contact("","","","",0);
	contactList:Contact[] = [];
	
	constructor(private contactService:ContactService) {}
	
	ngOnInit() {
		this.getList();
	}
	
	getList() {
		this.contactList = this.contactService.getList();
	}
	
	addContact() {
		this.contactService.addContact(this.contact);
		this.contact = new Contact("","","","",0);
		this.getList();
	}
	
	removeContact(id:number) {
		this.contactService.removeContact(id);
		this.getList();
	}
}
<form (ngSubmit)="addContact()" #contactForm="ngForm">
	<label for="firstname">First Name:</label>
	<input type="text"
			name="firstname"
			id="firstname"
			[(ngModel)]="contact.firstname"/>
	<br/>
	<label for="lastname">Last Name:</label>
	<input type="text"
			name="lastname"
			id="lastname"
			[(ngModel)]="contact.lastname"/>
	<br/>
	<label for="email">Email:</label>
	<input type="email"
			name="email"
			id="email"
			[(ngModel)]="contact.email"/>
	<br/>
	<label for="phone">Phone:</label>
	<input type="tel"
			name="phone"
			id="phone"
			[(ngModel)]="contact.phone"/>
	<br/>	
	<input type="submit" value="Add contact"/>
</form>
<table>
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Phone</th>
			<th>Remove</th>
		</tr>
	</thead>
	<tbody>
		<tr *ngFor="let c of contactList">
			<td>{{c.firstname}}</td>
			<td>{{c.lastname}}</td>
			<td>{{c.email}}</td>
			<td>{{c.phone}}</td>
			<td><button (click)="removeContact(c.id)">Remove</button></td>
		</tr>
	</tbody>
</table>
