// angular/k-shoppingapp/src/app/components/shoppingform.component.ts
import {Component,OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shopping.service';
import {LoginService} from '../services/login.service';
import {Router} from '@angular/router'

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html",
	styleUrls:["./shoppingform.component.css"]
})
export class ShoppingForm implements OnInit {
	
	item:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private shopping:ShoppingService,private login:LoginService,private router:Router) {}

	ngOnInit() {
		if(!this.login.isUserLogged()) {
			this.router.navigate(["/"])
		}
	}
	
	addItem() {
		this.shopping.addItem(this.item).subscribe(
			(data) => console.log(data),
			(error) => console.log(error),
			() => {
				this.item = new ShoppingItem("",0,0,0);
			}
		)
	}
}
<div class="container">
	<form (ngSubmit)="addItem()" #shoppingForm="ngForm">
		<div class="form-group">
			<label for="type" class="form-label">Type</label>
			<input type="text"
					name="type"
					id="type"
					class="form-control"
					[(ngModel)]="item.type"/>
		</div>
		<div class="form-group">
			<label for="count" class="form-label">Count</label>
			<input type="number"
					name="count"
					id="count"
					class="form-control"
					[(ngModel)]="item.count"/>
		</div>
		<div class="form-group">
			<label for="price" class="form-label">Price</label>
			<input type="number"
					name="price"
					id="price"
					class="form-control"
					[(ngModel)]="item.price"/>
		</div>
		<input type="submit" value="Add Item" class="btn btn-primary"/>
	</form>
</div>

// react/50_shopping_app/02_stage_login/frontend/src/components/ShoppingForm.js
import {useState} from 'react';

const ShoppingForm = (props) => {
	
	const [state,setState] = useState({
		type:"",
		count:0,
		price:0
	})
	
	const onChange = (event) => {
		setState((state) => {
			return {
				...state,
				[event.target.name]:event.target.value
			}
		})
	}
	
	const onSubmit = (event) => {
		event.preventDefault();
		let item = {
			...state
		};
		props.addItem(item);
		setState({
			type:"",
			count:0,
			price:0
		})
	}
	return(
		<div style={{
			margin:"auto",
			textAlign:"center",
			width:"40%",
			backgroundColor:"lightgreen"
		}}>
			<form className="mb-3" onSubmit={onSubmit}>
				<label htmlFor="type" className="form-label">Type</label>
				<input type="text"
						name="type"
						id="type"
						className="form-control"
						onChange={onChange}
						value={state.type}/>
				<label htmlFor="count" className="form-label">Count</label>
				<input type="number"
						name="count"
						id="count"
						className="form-control"
						onChange={onChange}
						value={state.count}/>
				<label htmlFor="price" className="form-label">Price</label>
				<input type="number"
						name="price"
						id="price"
						className="form-control"
						step="0.01"
						onChange={onChange}
						value={state.price}/>
				<input type="submit" className="btn btn-primary" value="Add"/>
			</form>	
		</div>
	)
}

export default ShoppingForm;
